config/routes.rb
Default::Application.routes.draw do

  devise_for :users
  
  resources :tags, only: [:index], :constraints => {:format => /(json)/}
  
  get :import, to: 'import#index'
  post :import, to: 'import#start'
  post :export, to: 'export#index'
  
  resources :users, path: 'users'
  
  namespace :api do
    match :posts_add, path: '/posts/add', to: 'posts#add', via: [:get, :post]
    match :posts_add_dep, path: '/posts_add.php', to: 'posts#add', via: [:get, :post]
    get :posts_all, path: '/posts/all', to: 'posts#all'
    get :posts_all_dep, path: '/posts_all.php', to: 'posts#all'
    match :posts_delete, path: '/posts/delete', to: 'posts#delete', via: [:get, :post]
    match :posts_delete_dep, path: '/posts_delete.php', to: 'posts#delete', via: [:get, :post]
    get :posts_update, path: '/posts/update', to: 'posts#update'
  end
  
  resources :posts, path: '/'
  root 'posts#index'
  
  resources :users, only: [], path: 'user' do
    get :posts, path: '/', controller: :posts, action: :index
    resources :tags, only: [], path: 'tag' do
      get :posts, path: '/', controller: :posts, action: :index
    end
  end
  
  resources :tags, only: [], path: 'tag' do
    get :posts, path: '/', controller: :posts, action: :index
  end
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="/logo.png" />
  <% if params['controller'] == 'posts' and params['action'] == 'index' %>
  	<%= auto_discovery_link_tag(:atom, {format: 'atom'}) %>
  <% end %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= nav_bar :responsive => true,
			:brand => image_tag('logo.png', :size => '30x30', :alt => 'Memor') + 'Memor' do %>
		
		<%= menu_group :pull => :right do %>
		    
		    <form class="navbar-form pull-left" method="get" action="<%= filter_link_without :q %>">
		    	<input name="q" placeholder="<%= t 'search' %>" type="text" class="input-medium search-query">
		    	<button type="submit" class="btn btn-inverse"><%= glyph('search') %></button>
		    </form>
		
			<% if user_signed_in? %>
			  <% if current_user.is_admin? %>
          	 <%= menu_item t('manage_users'), users_path %>
			  <% end %>
				<%= menu_item 'Bookmarklet', "javascript:(function(){
						x=document;a=encodeURIComponent(x.location.href);
						t=encodeURIComponent(x.title);
						d=encodeURIComponent(window.getSelection());
						open('"+new_post_path(:only_path => false)+"%3Furl='+a+'%26title='+t+'%26description='+d,'Memor','modal=1,status=0,scrollbars=1,toolbar=0,resizable=1,width=790,height=585,left='+(screen.width-790)/2+',top='+(screen.height-545)/2);
						})();"
				%>
				<%= menu_item t('import'), import_path %>
				<%= menu_item t('export'), export_path, :method => :post %>
				<%= menu_item t('logout'), destroy_user_session_path, :method => :delete %>        
			<% else %>
		  		<%= menu_item t('login'), new_user_session_path %>
			<% end %>
		<% end %>
			
	<% end %>

	<div class="container">
	
		<%= bootstrap_flash %>
	
		<%= yield %>
	</div>

</body>
</html>